name: CI/CD Pipeline

on:
  push:
    branches: 
      - main

jobs:
  test-and-build:
    name: Test and Build Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm ci

      - name: Transpile Code
        run: npm run build

      - name: Run Tests & Generate Code Coverage
        run: npm test
        
      - name: Codacy Coverage Reporter
        # You may pin to the exact commit or the version.
        # uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          # API project token to retrieve your remote Codacy configuration for the project being analyzed
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # API account token to retrieve your remote Codacy configuration for the project being analyzed
          # api-token: # optional
          # Optional comma separated list of coverage reports to send to Codacy
          # coverage-reports: # optional, default is 
          # Optionally force associating a language with your coverage report
          # language: # optional
          # Optionally force using a specific coverage report parser
          # force-coverage-parser: # optional

      # - name: Codecov
      #   uses: codecov/codecov-action@v2.1.0
      #   with:
      #     # Specify whether or not CI build should fail if Codecov runs into an error during upload
      #     fail_ci_if_error: true
